In [98]:
import numpy as np

In [103]:
def swap_rows(a, i, j):
    a[i, :], a[j, :] = list(a[j, :]).copy(), list(a[i, :]).copy()
    
def swap_columns(a, i, j):
    a[:, i], a[:, j] = list(a[:, j]).copy(), list(a[:, i]).copy()

def Gauss(a, b):
    n, sc = len(b), []
    if not(np.linalg.det(a)):
        print('Матрица вырожденная')
        return
    for i in range(n - 1):
        num = np.amax(abs(a)[i:, i:])
        x, j = np.where(abs(a) == num)
        sc.append([i, int(j[0])])
        swap_rows(a, i, int(x[0]))
        b[i], b[int(x[0])] = b[int(x[0])], b[i]
        swap_columns(a, i, int(j[0]))
        for k in range(i+1, n):
            r = a[k][i] / a[i][i]
            for l in range(i, n):
                a[k][l] -= a[i][l] * r
            b[k] -= b[i] * r
    u = np.zeros((n, 1))
    for i in range(n-1, -1, -1):
        s = 0
        for j in range(i+1, n):
            s += a[i][j] * u[j][0]
        u[i][0] = (b[i] - s) / a[i][i]

    k = np.shape(sc)[0]    
    for i in range(k-1, -1, -1):          
        u[sc[i][0]], u[sc[i][1]] = np.copy(u[sc[i][1]]), np.copy(u[sc[i][0]])
    return u

In [104]:
a = np.array([[1., 2., 0.], 
              [3., 4., 5.], 
              [0., 6., 7.]])
b = np.array([5., 6., 5.])
Gauss(a, b)

array([[ 1.],
       [ 2.],
       [-1.]])

In [105]:
a = np.array([[2., 3., 0.], 
              [4., 5., 6.], 
              [0., 7., 8.]])
b = np.array([8., 8., 6.])
Gauss(a, b)

array([[ 1.],
       [ 2.],
       [-1.]])

In [106]:
a = np.array([[3., 4., 0.], 
              [5., 6., 7.], 
              [0., 8., 9.]])
b = np.array([11., 10., 7.])
Gauss(a, b)

array([[ 1.],
       [ 2.],
       [-1.]])