In [113]:
import numpy as np

In [114]:
def norm(a, b, i):
    n = np.linalg.norm(a[i], ord=2)
    a[i] /= n
    b[i] /= n

In [115]:
def dot(*a):
    x = a[0]
    for i in range(1, len(a)):
        x = np.dot(x, a[i])
    return x

In [116]:
def ort_row(a, b):
    norm(a, b, 0)
    for i in range(1, len(a[0])):
        for j in range(i):
            a[i], b[i] = a[i] - dot(a[i], a[j], a[j]), b[i] - dot(a[i], a[j], b[j])
        norm(a, b, i)
    return np.dot(np.transpose(a), b)

In [120]:
a = np.array([[1., 2.], [3., 4.]])
b = np.array([3., 5.])

In [121]:
ort_row(a, b)

array([-1.,  2.])

In [122]:
a = np.array([[3., 4.], [5., 6.]])
b = np.array([2., 4.])

In [123]:
ort_row(a, b)

array([ 2., -1.])

In [124]:
a = np.array([[5., 6.], [7., 8.]])
b = np.array([9., 13.])

In [125]:
ort_row(a, b)

array([ 3., -1.])