In [89]:
import math
import numpy as np

In [90]:
def zeydel(A, b, x0): 
    for i in range(len(A)):
        s1 = sum([A[i][j] * x0[j] for j in range(i)])
        s2 = sum([A[i][j] * x0[j] for j in range(i + 1, len(A))])
        x0[i] = (b[i] - s1 - s2) / A[i][i]
    return(x0)

In [91]:
A1 = np.array([[2., -1., 0., 0.], [-1., 2., -1., 0.], [0., -1., 2., -1.], [0., 0., -1., 2.]])
b = np.array([-1., 1., 1., -1.])
x0 = np.array([1., 1., 1., 1.])
zeydel(A1, b, x0)

array([0.  , 1.  , 1.5 , 0.25])

In [92]:
A2 = np.array([[1, -1, 0, 0], [-1, 2, -1, 0], [0, -1, 2, -1], [0, 0, -1, 2]])
b = np.array([-1., 1., 1., -1.])
x0 = np.array([1., 1., 1., 1.])
zeydel(A2, b, x0)

array([0.  , 1.  , 1.5 , 0.25])

In [93]:
A3 = np.array([[2, -1, 0, 1], [-1, 2, -1, 0], [0, -1, 2, -1], [1, 0, -1, 2]])
b = np.array([-1., 1., 1., -1.])
x0 = np.array([1., 1., 1., 1.])
zeydel(A3, b, x0)

array([-0.5   ,  0.75  ,  1.375 ,  0.4375])